CREATE TABLE IF NOT EXISTS users (
	id BIGSERIAL PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	username VARCHAR(50) NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	role VARCHAR(30) NOT NULL DEFAULT 'player',
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
	koordinate_x INTEGER,
	koordinate_y INTEGER,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	last_login_at TIMESTAMPTZ,
	failed_login_attempts INTEGER NOT NULL DEFAULT 0,
	locked_until TIMESTAMPTZ
);